//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_MVVM.Models
{
    using System;
    using System.Collections.Generic;
    using QuanLyKho_MVVM.ViewModels;

    public partial class User : BaseViewModel
    {
        private int _Id { get; set; }
        private string _DisplayName { get; set; }
        private string _UserName { get; set; }
        private string _Password { get; set; }
        private int _IdRole { get; set; }

        public int Id { get => _Id; set { _Id = value; OnPropertyChanged(); } }
        public string DisplayName { get => _DisplayName; set { _DisplayName = value; OnPropertyChanged(); } }
        public string UserName { get => _UserName; set { _UserName = value; OnPropertyChanged(); } }
        public string Password { get => _Password; set { _Password = value; OnPropertyChanged(); } }
        public int IdRole { get => _IdRole; set { _IdRole = value; OnPropertyChanged(); } }

        public virtual UserRole UserRole { get; set; }
    }
}
