//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho_MVVM.Models
{
    using System;
    using QuanLyKho_MVVM.ViewModels;
    using System.Collections.Generic;

    public partial class Object : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.InputInfoes = new HashSet<InputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }

        private string _displayName;
        private string _qRCode;
        private string _barCode;
        private int _idUnit;
        private int _idSupplier;

        public string Id { get; set; }
        public string DisplayName { get => _displayName; set { _displayName = value; OnPropertyChanged(); } }
        public int IdUnit { get => _idUnit; set { _idUnit = value; OnPropertyChanged(); } }
        public int IdSuplier { get => _idSupplier; set { _idSupplier = value; OnPropertyChanged(); } }
        public string QRCode { get => _qRCode; set { _qRCode = value; OnPropertyChanged(); } }
        public string BarCode { get => _barCode; set { _barCode = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }

        private Unit _unit;
        private Supplier _supplier;
        public virtual Unit Unit { get => _unit; set { _unit = value; OnPropertyChanged(); } }
        public virtual Supplier Supplier { get => _supplier; set { _supplier = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
